version: '3.7'
services:
  nuxt.js:
    container_name: nakashun-com
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./nuxt:/nuxt:cached
    tty: true
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true